# Generated by Django 3.2.3 on 2024-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240428_1645'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(related_name='orders', to='user.Tag', verbose_name='Теги'),
        ),
    ]
